name: CI

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

    - name: Login to Docker Hub
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      if: github.ref_name == 'main'
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
      with:
        push: ${{ github.ref_name == 'main' }}
        tags: jkroepke/wixtoolset:latest
        load: ${{ github.ref_name != 'main' }}

    - name: Check out repository
      uses: actions/checkout@v4.3.1
      with:
        persist-credentials: 'false'

    - name: Test local action
      uses: ./
      with:
        run: |
          set -x
          echo "Testing WiX Toolset Docker Action"
          wix --version
          wix extension list
